application: cavamd
version: 1
runtime: php55
api_version: 1

handlers:
- url: /cavamd
  static_dir: cavamd
  
- url: /hwcore
  static_dir: hwcore

- url: /.*
  script: /index.php

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^\.idea$
- ^cavamd/data/media/avi/.*$
- ^nbproject/.*$
- ^run-local-gae.sh$
- ^update-gae.sh$
- ^cava-modules-sync.ffs_gui$

